services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-Wahide}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-https://wahide.id}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-https://api.wahide.id/api/v1}
        NEXT_PUBLIC_IAM_API_URL: ${NEXT_PUBLIC_IAM_API_URL:-https://api.wahide.id/api/v1}
        NEXT_PUBLIC_WHATSAPP_API_URL: ${NEXT_PUBLIC_WHATSAPP_API_URL:-https://api.wahide.id/api/v1}
        NEXT_PUBLIC_CAMPAIGN_API_URL: ${NEXT_PUBLIC_CAMPAIGN_API_URL:-https://api.wahide.id/api/v1}
        NEXT_PUBLIC_FINANCE_API_URL: ${NEXT_PUBLIC_FINANCE_API_URL:-https://api.wahide.id/api/v1}
        NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${NEXT_PUBLIC_TURNSTILE_SITE_KEY:-0x4AAAAAADOgaNLRGt1f6A6-}
    image: ${IMAGE_NAME:-ghcr.io/hidessh99/fontwahide:latest}
    container_name: ${CONTAINER_NAME:-wahide_frontend}
    deploy:
      resources:
        limits:
          cpus: ${CPUS:-1.5}
          memory: ${MEMORY_LIMIT:-1024M}
    restart: always
    ports:
      - "${HOST_IP:-0.0.0.0}:${WEB_HTTP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-Wahide}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://wahide.id}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://api.wahide.id/api/v1}
      - NEXT_PUBLIC_IAM_API_URL=${NEXT_PUBLIC_IAM_API_URL:-https://api.wahide.id/api/v1}
      - NEXT_PUBLIC_WHATSAPP_API_URL=${NEXT_PUBLIC_WHATSAPP_API_URL:-https://api.wahide.id/api/v1}
      - NEXT_PUBLIC_CAMPAIGN_API_URL=${NEXT_PUBLIC_CAMPAIGN_API_URL:-https://api.wahide.id/api/v1}
      - NEXT_PUBLIC_FINANCE_API_URL=${NEXT_PUBLIC_FINANCE_API_URL:-https://api.wahide.id/api/v1}
      - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY:-0x4AAAAAADOgaNLRGt1f6A6-}
      - TZ=${TZ:-Asia/Jakarta}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      createdBy: "bt_apps"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"